name: Deploy to Raspberry Pi Zero Worker

# Controls when the workflow will run
on:
  push:
    branches: [prod]
env:
  GH_REPO: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          file: .temp.env
      - run: |
          cd ~
          for i in $(cat .temp.env /etc/environment); do
            IFS=“=“ read -r var1 var2 <<< $i
            echo $var1 $var2
            tmp=$(mktemp)
            jq --arg $var1 $var2  '. += $ARGS.named' test.json > "$tmp" && mv -f "$tmp" test.json
            done
            wait
          rm .temp.env

  install:
    runs-on: self-hosted
    needs: build
    steps:
      - run: |
          [ -e $HOME/$GH_REPO ] && rm -r $HOME/$GH_REPO
          cp -r -u ${{ github.workspace }} $HOME/
          rm -r ${{ github.workspace }}

#   deploy:
#     runs-on: self-hosted
#     needs: build

#     steps:
#       # Kill gunicorn server, if running already
#       - name: Kill gunicorn
#         run: pkill gunicorn || true

#       # Run gunicorn server
#       - name: Run gunicorn
#         run: |
#           source flask-env/bin/activate
#           RUNNER_TRACKING_ID=""
#           gunicorn -w 1 -b 0.0.0.0:4000 app:app -D --log-file=gunicorn.log
