name: Deploy to Raspberry Pi Zero Worker

# Controls when the workflow will run
on:
  push:
    branches: [prod]
env:
  GH_REPO: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: thaind0/envfile@v1
        name: Create Env File
        id: export_env
        with:
          secrets: ${{ toJSON(secrets) }}
          file: .prod.env
      - run: |
          cp -r -u .prod.env $HOME/

  install:
    runs-on: self-hosted

    steps:
      - run: |
          [ -e $HOME/$GH_REPO ] && rm -r $HOME/$GH_REPO
          cp -r -u ${{ github.workspace }} $HOME/
          rm -r ${{ github.workspace }}
          export TESTING_VAR="Hello"

#   deploy:
#     runs-on: self-hosted
#     needs: build

#     steps:
#       # Kill gunicorn server, if running already
#       - name: Kill gunicorn
#         run: pkill gunicorn || true

#       # Run gunicorn server
#       - name: Run gunicorn
#         run: |
#           source flask-env/bin/activate
#           RUNNER_TRACKING_ID=""
#           gunicorn -w 1 -b 0.0.0.0:4000 app:app -D --log-file=gunicorn.log
